const { getDb } = require('./connection');
const { v4: uuidv4 } = require('uuid');

async function seed() {
  console.log('[seed] Populating database with sample opportunities...');
  const db = await getDb();

  const opportunities = [
    {
      id: uuidv4(),
      title: 'IT Modernization Support Services — Department of Veterans Affairs',
      industry: 'IT & Digital Services',
      naics_code: '541512',
      region: 'US',
      budget_min: 25000000,
      budget_max: 40000000,
      currency: 'USD',
      procurement_category: 'IT & Digital Services',
      opportunity_type: 'IDIQ',
      deadline: '2026-06-14',
      executive_summary_en: 'Multi-year IDIQ for modernization of legacy claims processing systems. Strong fit for small businesses with cloud migration and modernization past performance — set-aside for 8(a) participants.',
      executive_summary_tr: 'Geçmiş claim işlem sistemlerinin modernizasyonu için çok yıllı IDIQ. Bulut göçü ve modernizasyon geçmiş performansı olan küçük işletmeler için güçlü uyum — 8(a) katılımcılarına set-aside.',
      solicitation_number: 'VA-2026-ITM-0042',
      agency_name: 'Department of Veterans Affairs — Office of Information & Technology',
      performance_location: 'Washington, D.C. Metro Area + Remote',
      source: 'sam.gov',
      source_id: 'SAM-2026-05142',
      status: 'published',
      featured: 1,
    },
    {
      id: uuidv4(),
      title: 'Healthcare Data Analytics Platform — HHS',
      industry: 'IT & Digital Services',
      naics_code: '541511',
      region: 'US',
      budget_min: 7500000,
      budget_max: 8500000,
      currency: 'USD',
      procurement_category: 'IT & Digital Services',
      opportunity_type: 'RFP',
      deadline: '2026-05-30',
      executive_summary_en: '5-year contract for population-health analytics. Past performance in CMS data environments preferred.',
      executive_summary_tr: 'Nüfus sağlığı analitiği için 5 yıllık sözleşme. CMS veri ortamlarında geçmiş performans tercih edilir.',
      solicitation_number: 'HHS-2026-PHA-0198',
      agency_name: 'Department of Health & Human Services',
      performance_location: 'Bethesda, MD',
      source: 'sam.gov',
      source_id: 'SAM-2026-04712',
      status: 'published',
      featured: 0,
    },
    {
      id: uuidv4(),
      title: 'Construction Management — GSA Mid-Atlantic',
      industry: 'Construction & Infrastructure',
      naics_code: '236220',
      region: 'US',
      budget_min: 11000000,
      budget_max: 12500000,
      currency: 'USD',
      procurement_category: 'Construction & Infrastructure',
      opportunity_type: 'RFP',
      deadline: '2026-06-18',
      executive_summary_en: 'Federal building renovations across DC, MD, VA. HUBZone set-aside. Multi-phase renovation program.',
      executive_summary_tr: 'DC, MD, VA\'da federal bina renovasyonları. HUBZone set-aside. Çok aşamalı renovasyon programı.',
      solicitation_number: 'GSA-MA-2026-REN-0331',
      agency_name: 'General Services Administration — Mid-Atlantic Region',
      performance_location: 'Washington D.C., Maryland, Virginia',
      source: 'sam.gov',
      source_id: 'SAM-2026-05301',
      status: 'published',
      featured: 0,
    },
    {
      id: uuidv4(),
      title: 'Cybersecurity Operations Support — SOC Services',
      industry: 'IT & Digital Services',
      naics_code: '541519',
      region: 'US',
      budget_min: 7500000,
      budget_max: 8500000,
      currency: 'USD',
      procurement_category: 'IT & Digital Services',
      opportunity_type: 'RFP',
      deadline: '2026-05-30',
      executive_summary_en: 'SOC operations, threat monitoring, and incident response for DHS CISA. 5-year base + options. Reliability security clearance required.',
      executive_summary_tr: 'DHS CISA için SOC operasyonları, tehdit izleme ve olay müdahalesi. 5 yıl + opsiyonlar. Güvenilirlik güvenlik izni gerekli.',
      solicitation_number: 'CISA-2026-SOC-0087',
      agency_name: 'Cybersecurity & Infrastructure Security Agency (CISA)',
      performance_location: 'Arlington, VA',
      source: 'sam.gov',
      source_id: 'SAM-2026-04892',
      status: 'published',
      featured: 0,
    },
    {
      id: uuidv4(),
      title: 'Embassy Compound Renovation — Multiple Locations',
      industry: 'Construction & Infrastructure',
      naics_code: '236220',
      region: 'US',
      budget_min: 11000000,
      budget_max: 13000000,
      currency: 'USD',
      procurement_category: 'Construction & Infrastructure',
      opportunity_type: 'RFP',
      deadline: '2026-06-18',
      executive_summary_en: 'Infrastructure and interior upgrades across State Department facilities in Europe and the Middle East. HUBZone set-aside. Experience with occupied diplomatic facilities preferred.',
      executive_summary_tr: 'Avrupa ve Orta Doğu\'daki Dışişleri Bakanlığı tesislerinde altyapı ve iç mekan yükseltmeleri. HUBZone set-aside. İşlek diplomatik tesisler konusunda deneyim tercih edilir.',
      solicitation_number: 'DOS-2026-EMB-0155',
      agency_name: 'Department of State — Bureau of Overseas Buildings Operations',
      performance_location: 'Multiple — Europe & Middle East',
      source: 'sam.gov',
      source_id: 'SAM-2026-05403',
      status: 'published',
      featured: 1,
    },
    {
      id: uuidv4(),
      title: 'Military Base Maintenance & Repair — OCONUS',
      industry: 'Construction & Infrastructure',
      naics_code: '236210',
      region: 'US',
      budget_min: 17000000,
      budget_max: 19000000,
      currency: 'USD',
      procurement_category: 'Construction & Infrastructure',
      opportunity_type: 'RFP',
      deadline: '2026-07-03',
      executive_summary_en: 'Ongoing maintenance and repair for U.S. military installations outside the continental U.S. (OCONUS). Multi-year base contract with options. Strong fit for contractors with prior overseas military project experience.',
      executive_summary_tr: 'Kıta dışındaki ABD askeri tesisleri (OCONUS) için süregelen bakım ve onarım — Avrupa ve Orta Doğu\'daki üsleri kapsıyor. Opsiyon yıllı çok yıllı temel sözleşme.',
      solicitation_number: 'USACE-2026-OCON-0299',
      agency_name: 'U.S. Army Corps of Engineers — OCONUS Division',
      performance_location: 'Multiple — Europe & Middle East',
      source: 'sam.gov',
      source_id: 'SAM-2026-05672',
      status: 'published',
      featured: 0,
    },
    {
      id: uuidv4(),
      title: 'Warehouse & Distribution Services — Mid-Atlantic Region',
      industry: 'Supply Chain & Logistics',
      naics_code: '493110',
      region: 'US',
      budget_min: 20000000,
      budget_max: 24000000,
      currency: 'USD',
      procurement_category: 'Supply Chain & Logistics',
      opportunity_type: 'RFP',
      deadline: '2026-06-28',
      executive_summary_en: 'Warehousing, inventory management, and distribution for military parts and equipment. 3-year base contract with 2 option years.',
      executive_summary_tr: 'Askeri parçalar ve ekipman için depolama, envanter yönetimi ve dağıtım. 2 opsiyon yıllı 3 yıllık temel sözleşme.',
      solicitation_number: 'DLA-2026-WH-0177',
      agency_name: 'Defense Logistics Agency',
      performance_location: 'Mid-Atlantic Region, USA',
      source: 'sam.gov',
      source_id: 'SAM-2026-05510',
      status: 'published',
      featured: 0,
    },
    {
      id: uuidv4(),
      title: 'Program Management & Translation Services — State Dept.',
      industry: 'Professional Services',
      naics_code: '541930',
      region: 'US',
      budget_min: 4500000,
      budget_max: 5500000,
      currency: 'USD',
      procurement_category: 'Professional Services',
      opportunity_type: 'RFP',
      deadline: '2026-06-22',
      executive_summary_en: 'Multilingual program support, translation (Turkish, Arabic, Farsi among others), and international program management. Small business set-aside. Ideal for bilingual teams.',
      executive_summary_tr: 'Çok dilli program desteği, çeviri (Türkçe, Arapça, Farsça dahil) ve uluslararası program yönetimi. Küçük işletme set-aside. İki dilli ekipler için ideal.',
      solicitation_number: 'DOS-2026-TRANS-0211',
      agency_name: 'Department of State — Bureau of Administration',
      performance_location: 'Washington, D.C. + Overseas Posts',
      source: 'sam.gov',
      source_id: 'SAM-2026-05588',
      status: 'published',
      featured: 0,
    },
    {
      id: uuidv4(),
      title: 'Vehicle Maintenance & Fleet Support — Overseas Federal Facilities',
      industry: 'Supply Chain & Logistics',
      naics_code: '811111',
      region: 'US',
      budget_min: 8000000,
      budget_max: 9500000,
      currency: 'USD',
      procurement_category: 'Supply Chain & Logistics',
      opportunity_type: 'RFP',
      deadline: '2026-07-10',
      executive_summary_en: 'Preventive maintenance, repair, and fleet management for vehicle fleets at U.S. embassies and consulates abroad. Multiple performance locations across Europe and the Middle East.',
      executive_summary_tr: 'Yurt dışındaki ABD büyükelçilikleri ve konsolosluklarındaki araç filoları için önleyici bakım, onarım ve filo yönetimi desteği.',
      solicitation_number: 'GSA-FM-2026-OVS-0091',
      agency_name: 'GSA — Fleet Management Division',
      performance_location: 'Multiple — Europe & Middle East',
      source: 'sam.gov',
      source_id: 'SAM-2026-05842',
      status: 'published',
      featured: 0,
    },
    {
      id: uuidv4(),
      title: 'Cybersecurity Advisory Services — DND Units',
      industry: 'IT & Digital Services',
      naics_code: null,
      region: 'Canada',
      budget_min: 2700000,
      budget_max: 3000000,
      currency: 'CAD',
      procurement_category: 'Defense & Security',
      opportunity_type: 'Standing Offer',
      deadline: '2026-06-12',
      executive_summary_en: 'Cyber risk assessments and security architecture review across DND units. 3-year contract with 2 option years. Open to qualified Canadian entities. Reliability clearance required.',
      executive_summary_tr: 'DND birimleri genelinde siber risk değerlendirmeleri ve güvenlik mimarisi incelemesi. 2 opsiyon yıllı 3 yıllık sözleşme. Nitelikli Kanada şirketlerine açık.',
      solicitation_number: 'DND-2026-CYBER-0044',
      agency_name: 'Department of National Defence — Canada',
      performance_location: 'Ottawa, ON + Regional Bases',
      source: 'canadabuys',
      source_id: 'CB-2026-04123',
      status: 'published',
      featured: 0,
    },
    {
      id: uuidv4(),
      title: 'IT Professional Services — Digital Transformation',
      industry: 'IT & Digital Services',
      naics_code: null,
      region: 'Canada',
      budget_min: 4500000,
      budget_max: 5000000,
      currency: 'CAD',
      procurement_category: 'IT & Digital Services',
      opportunity_type: 'Standing Offer',
      deadline: '2026-06-05',
      executive_summary_en: 'Multi-year standing offer for digital transformation and enterprise application support across federal departments. Accessible via ProServices SA.',
      executive_summary_tr: 'Federal departmanlar genelinde dijital dönüşüm ve kurumsal uygulama desteği için çok yıllı standing offer. ProServices SA üzerinden erişilebilir.',
      solicitation_number: 'PSPC-2026-PROS-0128',
      agency_name: 'Public Services and Procurement Canada',
      performance_location: 'National Capital Region, ON/QC',
      source: 'canadabuys',
      source_id: 'CB-2026-03904',
      status: 'published',
      featured: 0,
    },
    {
      id: uuidv4(),
      title: 'Mixed-Use Development — Miami Brickell',
      industry: 'Real Estate',
      naics_code: null,
      region: 'US',
      budget_min: 18000000,
      budget_max: 25000000,
      currency: 'USD',
      procurement_category: 'Real Estate',
      opportunity_type: 'Equity',
      deadline: '2026-07-31',
      executive_summary_en: 'Co-investment opportunity in Miami Brickell mixed-use development. Sponsor with 12-year track record. FIRPTA-compliant structuring available.',
      executive_summary_tr: 'Miami Brickell karma kullanım projesinde ortak yatırım fırsatı. 12 yıllık geçmişe sahip sponsor. FIRPTA uyumlu yapılandırma mevcut.',
      solicitation_number: null,
      agency_name: null,
      performance_location: 'Miami, FL',
      source: 'manual',
      source_id: null,
      status: 'published',
      featured: 0,
    },
  ];

  const insertOpp = (o) => {
    db.prepare(`
      INSERT OR IGNORE INTO opportunities
        (id, title, industry, naics_code, region, budget_min, budget_max, currency,
         procurement_category, opportunity_type, deadline, executive_summary_en,
         executive_summary_tr, location_display,
         solicitation_number, agency_name, performance_location,
         source, source_id, source_url, status, featured)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      o.id, o.title, o.industry, o.naics_code ? String(o.naics_code) : null, o.region,
      o.budget_min, o.budget_max, o.currency,
      o.procurement_category, o.opportunity_type, o.deadline,
      o.executive_summary_en, o.executive_summary_tr,
      o.location_display || null,
      o.solicitation_number, o.agency_name, o.performance_location,
      o.source, o.source_id, o.source_url || null, o.status, o.featured,
    );
  };

  for (const o of opportunities) {
    insertOpp(o);
  }

  const count = db.prepare('SELECT COUNT(*) as total FROM opportunities').get();
  console.log(`[seed] Done. ${count.total} opportunities in database.`);
}

seed().then(() => process.exit(0)).catch(err => {
  console.error('[seed] Failed:', err);
  process.exit(1);
});
